{
    'name': 'HMS Prescription',
    'version': '1.0.1',
    'category': 'HMS',
    'sequence': -87,
    'summary': 'Base Module for Hospital Management',
    'description': """
        This module adds Prescription functionality
    """,
    'author': 'Torq-Shade',
    'website': 'www.odoo.com',
    'depends': ['banastech_hms', 'sale', 'stock', 'product', 'purchase','board'],
    'data': [
        'views/hms_family_view.xml',
        'views/hms_prescription_order_view.xml',
        'views/hms_indoor.xml',
        'views/hms_prescription_line_view.xml',
        'views/hms_patient_medication_view.xml',
        'views/menu_view.xml',
        'views/hms_patient_view.xml',
        # 'report/report_hms_prescription.xml',
        # 'report/grn_report.xml',
        'security/ir.model.access.csv',
        'data/prescription_order_data.xml',
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}