from . import patient
from . import appointment
from . import patient_tag
from . import doctor
from . import product_template
from . import cancle_appointment
from . import diseases
from . import diseases_gene
from . import medicament
from . import drug
from . import surgery
from . import account_move_inherit